name: Docker

on:
  push:
    branches:
      - main
      - master
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  docker:
    name: Build and Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: benfrisbie/docker-tag-build-push-action@v1
        with:
          context: .
          file: Dockerfile
